version: '3'


services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      datapipeline:
        ipv4_address: 172.18.0.3
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://172.18.0.4:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.4:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      datapipeline:
        ipv4_address: 172.18.0.4
  minio:
    image: quay.io/minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY_FILE: /run/secrets/minio_user
      MINIO_SECRET_KEY_FILE: /run/secrets/minio_password
    secrets:
      - minio_user
      - minio_password
    command: server /data --console-address ":9090"
    networks:
      datapipeline:
        ipv4_address: 172.18.0.5
  sparkmaster:
    image: sparkmaster:1.0
    container_name: sparkmaster
    hostname: sparkmaster
    tty: true
    ports:
      - '8080:8080'
      - '7077:7077'
    depends_on:
      - kafka
      - minio
    networks:
      datapipeline:
        ipv4_address: 172.18.0.6
  sparkworker:
    image: sparkworker:1.0
    container_name: sparkworker
    hostname: sparkworker
    environment:
      MASTER_HOST_NAME: spark://172.18.0.6:7077
      WORKER_MEMORY: 1G
    tty: true
    ports:
      - '8081:8081'
    depends_on:
      - sparkmaster
    networks:
      datapipeline:
        ipv4_address: 172.18.0.7
  sparkclient:
    image: sparkclient:1.0
    container_name: sparkclient
    hostname: sparkclient
    ports:
      - '4040:4040'
    depends_on:
      - sparkmaster
    env_file:
      - .env
    networks:
      datapipeline:
        ipv4_address: 172.18.0.8


secrets:
  minio_user:
    file: ./secrets/minio_user.txt
  minio_password:
    file: ./secrets/minio_password.txt

volumes:
  minio_storage: {}

networks:
    datapipeline:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"