FROM sparkbase:1.0


## Setting up my code
COPY streaming/ /opt/poc_kafka_delta/streaming/
COPY main.py /opt/poc_kafka_delta
COPY simulate_kafka.py /opt/poc_kafka_delta
COPY spark-defaults.conf /opt/spark/conf

## Execute the final shell script to run our job
CMD $SPARK_HOME/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1,io.delta:delta-core_2.12:2.1.1,com.amazonaws:aws-java-sdk:1.12.341,org.apache.hadoop:hadoop-aws:3.3.4,org.apache.hadoop:hadoop-common:3.3.4 --conf spark.delta.logStore.class=org.apache.spark.sql.delta.storage.S3SingleDriverLogStore /opt/poc_kafka_delta/main.py