version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY_FILE: user
      MINIO_SECRET_KEY_FILE: password

    command: server /data --console-address ":9090"

  sparkmaster:
    image: sparkmaster:1.0
    container_name: sparkmaster
    hostname: sparkmaster
    tty: true
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - spark_packages:/root/.ivy2/jars
      - spark_cache:/root/.ivy2/cache
    depends_on:
      - kafka
      - minio

  sparkworker:
    image: sparkworker:1.0
    container_name: sparkworker
    hostname: sparkworker
    environment:
      MASTER_HOST_NAME: spark://localhost:7077
      WORKER_MEMORY: 1G
    tty: true
    ports:
      - '8081:8081'
    volumes:
      - spark_packages:/root/.ivy2/jars
      - spark_cache:/root/.ivy2/cache
    depends_on:
      - sparkmaster

  sparkclient:
    image: sparkclient:1.0
    container_name: sparkclient
    hostname: sparkclient
    ports:
      - '4040:4040'
    depends_on:
      - sparkmaster
    volumes:
      - spark_packages:/root/.ivy2/jars
      - spark_cache:/root/.ivy2/cache
    env_file:
      - .env
        




volumes:
  minio_storage:  {}
  spark_packages: {}
  spark_cache:    {}
