name: spark_streaming
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - autopep8=2.0.0
  - backcall=0.2.0
  - black=22.10.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - click=8.1.3
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.15.2
  - ipython=8.4.0
  - isort=5.11.2
  - jedi=0.18.1
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - openssl=3.0.7
  - packaging=21.3
  - parso=0.8.3
  - pathspec=0.10.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - platformdirs=2.6.0
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pyflakes=3.0.1
  - pygments=2.11.2
  - pyparsing=3.0.9
  - python=3.9.15
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.1.1
  - typing_extensions=4.4.0
  - tzdata=2022f
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - astroid==2.12.13
    - delta-spark==2.1.1
    - dill==0.3.6
    - findspark==2.0.1
    - importlib-metadata==5.0.0
    - kafka-python==2.0.2
    - lazy-object-proxy==1.8.0
    - mccabe==0.7.0
    - minio==7.1.12
    - numpy==1.23.4
    - pandas==1.5.1
    - pep8==1.7.1
    - py4j==0.10.9.5
    - pydocstringformatter==0.7.2
    - pylint==2.15.8
    - pyspark==3.3.1
    - python-dotenv==0.21.0
    - pytz==2022.6
    - tomlkit==0.11.6
    - urllib3==1.26.12
    - wrapt==1.14.1
    - zipp==3.10.0
