channels:
  - defaults
  - conda-forge
  - pypi
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jedi=0.18.1
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - openssl=1.1.1s
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.9
  - python=3.9.13
  - python-dateutil=2.8.2
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - tzdata=2022f
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - delta-spark==2.1.1
    - findspark==2.0.1
    - importlib-metadata==5.0.0
    - kafka-python==2.0.2
    - minio==7.1.12
    - numpy==1.23.4
    - pandas==1.5.1
    - py4j==0.10.9.5
    - pyspark==3.3.1
    - python-dotenv==0.21.0
    - pytz==2022.6
    - urllib3==1.26.12
    - zipp==3.10.0
