import json


from kafka import KafkaProducer
from kafka.errors import KafkaError
RUNS = 100000

bootstrap_servers = ['localhost:9092']
topicName = 'cdc_test_topics'
producer = KafkaProducer(bootstrap_servers = bootstrap_servers)
# Asynchronous by default
for _ in range(RUNS):
    future = producer.send(topicName, r"""
        {"schema":{
        "type":"struct",
        "fields":[
            {
                "type":"struct",
                "fields":[
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int32",
                                "optional":false,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":false,
                        "name":"id",
                        "field":"id"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int32",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"pin",
                        "field":"pin"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"status",
                        "field":"status"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int64",
                                "optional":true,
                                "name":"io.debezium.time.Timestamp",
                                "version":1,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"created",
                        "field":"created"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"creator_type",
                        "field":"creator_type"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"creator",
                        "field":"creator"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int64",
                                "optional":true,
                                "name":"io.debezium.time.Timestamp",
                                "version":1,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"updated",
                        "field":"updated"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"updator_type",
                        "field":"updator_type"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"updator",
                        "field":"updator"
                    }
                ],
                "optional":true,
                "name":"dbserver1.public.customer.Value",
                "field":"before"
            },
            {
                "type":"struct",
                "fields":[
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int32",
                                "optional":false,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":false,
                        "name":"id",
                        "field":"id"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int32",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"pin",
                        "field":"pin"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"status",
                        "field":"status"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int64",
                                "optional":true,
                                "name":"io.debezium.time.Timestamp",
                                "version":1,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"created",
                        "field":"created"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"creator_type",
                        "field":"creator_type"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"creator",
                        "field":"creator"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"int64",
                                "optional":true,
                                "name":"io.debezium.time.Timestamp",
                                "version":1,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"updated",
                        "field":"updated"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"updator_type",
                        "field":"updator_type"
                    },
                    {
                        "type":"struct",
                        "fields":[
                            {
                                "type":"string",
                                "optional":true,
                                "field":"value"
                            },
                            {
                                "type":"boolean",
                                "optional":false,
                                "field":"set"
                            }
                        ],
                        "optional":true,
                        "name":"updator",
                        "field":"updator"
                    }
                ],
                "optional":true,
                "name":"dbserver1.public.customer.Value",
                "field":"after"
            },
            {
                "type":"struct",
                "fields":[
                    {
                        "type":"string",
                        "optional":false,
                        "field":"version"
                    },
                    {
                        "type":"string",
                        "optional":false,
                        "field":"connector"
                    },
                    {
                        "type":"string",
                        "optional":false,
                        "field":"name"
                    },
                    {
                        "type":"int64",
                        "optional":false,
                        "field":"ts_ms"
                    },
                    {
                        "type":"string",
                        "optional":true,
                        "name":"io.debezium.data.Enum",
                        "version":1,
                        "parameters":{
                            "allowed":"true,last,false"
                        },
                        "default":"false",
                        "field":"snapshot"
                    },
                    {
                        "type":"string",
                        "optional":false,
                        "field":"db"
                    },
                    {
                        "type":"string",
                        "optional":true,
                        "field":"sequence"
                    },
                    {
                        "type":"string",
                        "optional":false,
                        "field":"schema"
                    },
                    {
                        "type":"string",
                        "optional":false,
                        "field":"table"
                    },
                    {
                        "type":"string",
                        "optional":true,
                        "field":"txId"
                    },
                    {
                        "type":"string",
                        "optional":true,
                        "field":"lsn"
                    },
                    {
                        "type":"int64",
                        "optional":true,
                        "field":"xmin"
                    }
                ],
                "optional":false,
                "name":"io.debezium.connector.postgresql.Source",
                "field":"source"
            },
            {
                "type":"string",
                "optional":false,
                "field":"op"
            },
            {
                "type":"int64",
                "optional":true,
                "field":"ts_ms"
            },
            {
                "type":"struct",
                "fields":[
                    {
                        "type":"string",
                        "optional":false,
                        "field":"id"
                    },
                    {
                        "type":"int64",
                        "optional":false,
                        "field":"total_order"
                    },
                    {
                        "type":"int64",
                        "optional":false,
                        "field":"data_collection_order"
                    }
                ],
                "optional":true,
                "field":"transaction"
            }
        ],
        "optional":false,
        "name":"dbserver1.public.customer.Envelope"
    },
    "payload":{
        "before":null,
        "after":{
            "id":{
                "value":1,
                "set":true
            },
            "pin":null,
            "status":null,
            "created":null,
            "creator_type":null,
            "creator":{
                "value":"Zain",
                "set":true
            },
            "updated":null,
            "updator_type":null,
            "updator":null
        },
        "source":{
            "version":"1.7.0.13-BETA",
            "connector":"yugabytedb",
            "name":"dbserver1",
            "ts_ms":6146305941239,
            "snapshot":"false",
            "db":"testdatabase",
            "sequence":"[\"0:0::0:0\",\"3:6::0:0\"]",
            "schema":"public",
            "table":"customer",
            "txId":"",
            "lsn":"3:6::0:0",
            "xmin":null
        },
        "op":"u",
        "ts_ms":1667832425466,
        "transaction":null
    }

}""".encode('utf-8')).get(timeout=30)
