apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9090
          env:
            - name: MINIO_ROOT_USER
              value: user
            - name: MINIO_ROOT_PASSWORD
              value: password
          image: quay.io/minio/minio:latest
          name: minio
          ports:
            - containerPort: 9000
            - containerPort: 9090
          volumeMounts:
            - mountPath: /data
              name: minio-storage
      hostname: minio
      restartPolicy: Always
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-storage
