apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  clusterIP: 10.97.0.3
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: minio
