apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: spark-cache
  annotations:
    "helm.sh/resource-policy": keep
  name: spark-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
