apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: sparkmaster
  name: sparkmaster
spec:
  type: ClusterIP 
  clusterIP: 10.10.0.4
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "7077"
      port: 7077
      targetPort: 7077
  selector:
    io.kompose.service: sparkmaster
