apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: spark-packages
  annotations:
    "helm.sh/resource-policy": keep
  name: spark-packages
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
