apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparkworker1
  name: sparkworker1-service
spec:
  clusterIP: 10.97.0.5
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: sparkworker1
