apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparkclient
  name: sparkclient-service
  namespace: {{ .Values.global.namespace }} 
spec:
  clusterIP: {{ .Values.spark.client_config.ip}}
  ports:
    - name: client-web-ui-port
      port: {{ .Values.spark.client_config.web_ui_port }}
      targetPort: 4040
    - name: driver-port
      port: {{ .Values.spark.client_config.driver_port }}
      targetPort: {{.Values.spark.client_config.driver_port }}
    - name: blockmanager-port
      port: {{ .Values.spark.client_config.block_manager_port }}
      targetPort: {{ .Values.spark.client_config.block_manager_port }}
  selector:
    app: sparkclient
