apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparkmaster
  name: sparkmaster-service
  namespace: {{ .Values.global.namespace }}  
spec:
  clusterIP: {{.Values.spark.master_config.ip}}
  ports:
    - name: master-web-ui-port
      port: {{.Values.spark.master_config.web_ui_port}}
      targetPort: 8080
    - name: master-port
      port: {{.Values.spark.master_config.master_port}}
      targetPort: 7077
  selector:
    app: sparkmaster
