apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sparkclient
  name: sparkclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sparkclient
    spec:
      containers:
        - env:
            - name: CustomerTableConfig
              valueFrom:
                configMapKeyRef:
                  key: CustomerTableConfig
                  name: env
            - name: KafkaConsumerConfig
              valueFrom:
                configMapKeyRef:
                  key: KafkaConsumerConfig
                  name: env
            - name: KafkaServer
              valueFrom:
                configMapKeyRef:
                  key: KafkaServer
                  name: env
            - name: S3EndPoint
              valueFrom:
                configMapKeyRef:
                  key: S3EndPoint
                  name: env
            - name: S3Password
              valueFrom:
                configMapKeyRef:
                  key: S3Password
                  name: env
            - name: S3USER
              valueFrom:
                configMapKeyRef:
                  key: S3USER
                  name: env
            - name: SourceBucket
              valueFrom:
                configMapKeyRef:
                  key: SourceBucket
                  name: env
            - name: TopicName
              valueFrom:
                configMapKeyRef:
                  key: TopicName
                  name: env
            - name: MASTER_HOST_NAME
              value: spark://10.97.0.4:7077
            - name: "SPARK_LOCAL_IP"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "status.podIP"
          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
          image: sparkclient:1.0
          name: sparkclient
          ports:
            - containerPort: 4040
            - containerPort: 4000
          volumeMounts:
            - mountPath: /root/.ivy2/jars
              name: spark-packages
            - mountPath: /root/.ivy2/cache
              name: spark-cache
      hostname: sparkclient-service
      restartPolicy: Always
      volumes:
        - name: spark-packages
          persistentVolumeClaim:
            claimName: spark-packages
        - name: spark-cache
          persistentVolumeClaim:
            claimName: spark-cache
