apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparkclient
  name: sparkclient-service
spec:
  clusterIP: 10.97.0.6
  ports:
    - name: "4040"
      port: 4040
      targetPort: 4040
  selector:
    app: sparkclient
