apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparkmaster
  name: sparkmaster-service
spec:
  clusterIP: 10.97.0.4
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "7077"
      port: 7077
      targetPort: 7077
  selector:
    app: sparkmaster
