apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sparkworker1
  name: sparkworker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkworker1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sparkworker1
    spec:
      containers:
        - env:
            - name: MASTER_HOST_NAME
              value: spark://10.97.0.4:7077
            - name: WORKER_MEMORY
              value: 1G
            - name: WORKER_CORES
              value: '2'
          image: sparkworker:1.0
          name: sparkworker1
          ports:
            - containerPort: 8081
          tty: true
          volumeMounts:
            - mountPath: /root/.ivy2/jars
              name: spark-packages
            - mountPath: /root/.ivy2/cache
              name: spark-cache
      hostname: sparkworker1
      restartPolicy: Always
      volumes:
        - name: spark-packages
          persistentVolumeClaim:
            claimName: spark-packages
        - name: spark-cache
          persistentVolumeClaim:
            claimName: spark-cache
