apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparkworker1
  name: sparkworker1-service
spec:
  clusterIP: {{.Values.spark.worker1_config.ip}}
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: sparkworker1
