global:
  namespace: default

kafka:
  kafkaServer: kafka-0.kafka-headless.default.svc.cluster.local:9092
  consumer_config: '{"failOnDataLoss":"false" , "minOffsetsPerTrigger":30}'

s3:
  endPointLoc: 10.97.0.3:9000
  user: user
  password: password
  source_bucket: test

spark:
  master_image:
    registry: quay.io/oknah
    repository: sparkmaster
    tag: "1.0"
    digest: ""
  worker_image:
    registry: quay.io/oknah
    repository: sparkworker
    tag: "1.0"
    digest: ""
  client_image:
    registry: quay.io/oknah
    repository: sparkclient
    tag: "1.2"
    digest: ""

  client_config:
    ip: 10.97.0.6
    web_ui_port: 4040
    driver_port: 40207
    block_manager_port: 40208
    node_resource:
      requests:
        memory: 64M
        cpu: 250m
      limits:
        memory: 1.5G
        cpu: 500m

  master_config:
    ip: 10.97.0.4
    web_ui_port: 9001
    master_port: 7077
    node_resource:
      requests:
        memory: 64M
        cpu: 250m
      limits:
        memory: 1.5G
        cpu: 500m

  all_workers:
    web_ui_port: 8081
    executor_cores: "1"
    executor_memory: 2000m
    min_executors: "0"
    max_executors: "1"

  worker1_config:
    ip: 10.97.0.5
    spark_node_cores: "1"
    spark_node_memory: 2g
    node_resource:
      requests:
        memory: 64M
        cpu: 250m
      limits:
        memory: 6G
        cpu: 2000m

  worker2_config:
    ip: 10.97.0.10
    spark_node_cores: "1"
    spark_node_memory: 2g
    node_resource:
      requests:
        memory: 64M
        cpu: 250m
      limits:
        memory: 6G
        cpu: 2000m
