



kafka:
  kafkaServer: my-release-kafka.default.svc.cluster.local:9092
  topic_name: cdc_test_topics
  consumer_config: '{"failOnDataLoss":"false"}'

s3:
  endPointLoc: 10.97.0.3:9000
  user: user
  password: password
  source_bucket: test

spark:
  master_image:
    registry: quay.io/oknah
    repository: sparkmaster
    tag: '1.0'
    digest: ""
  worker_image: 
    registry: quay.io/oknah
    repository: sparkworker
    tag: '1.0'
    digest: ""
  client_image:
    registry: quay.io/oknah
    repository: sparkclient
    tag: '1.0'
    digest: ""
  master_config:
    ip: 10.97.0.4
  worker1_config:
    ip: 10.97.0.5
    cores: '2'
    memory: 1G
    
