apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio-storage
  annotations:
    "helm.sh/resource-policy": keep
  name: minio-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
